# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Mi Primera CI

on:
  push:
    branches: [ "main" ]

jobs:
  mi-primer-job:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: 2. Configurar Node.js
      uses: actions/setup-node@v4
      with:
          cache: 'npm'
  
    - run: npm install --legacy-peer-deps
    - run: npm run lint
    - run: npm test
    - run: npm run build
    
    